### ISSUE TITLE
App crashes on Q Beta 1

### ISSUE THREAD

**Issue by anilgorthy** [square/reader-sdk-android-quickstart#11]
I realize Q Beta 1 was announced only a few days back but when I run this sample on an Android Q Emulator, the app crashes with the following stack trace:

`2019-03-21 08:49:22.607 10323-10323/com.example.readersdk E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.readersdk, PID: 10323
    io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: Invalid primitive conversion from long to int
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:704)
        at io.reactivex.internal.functions.Functions$OnErrorMissingConsumer.accept(Functions.java:701)
        at io.reactivex.internal.observers.ConsumerSingleObserver.onError(ConsumerSingleObserver.java:46)
        at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onError(SingleFlatMap.java:90)
        at io.reactivex.internal.observers.ResumeSingleObserver.onError(ResumeSingleObserver.java:51)
        at io.reactivex.internal.disposables.EmptyDisposable.error(EmptyDisposable.java:78)
        at io.reactivex.internal.operators.single.SingleError.subscribeActual(SingleError.java:42)
        at io.reactivex.Single.subscribe(Single.java:3438)
        at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:80)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69)
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: io.reactivex.exceptions.OnErrorNotImplementedException: The exception was not handled due to missing onError handler in the subscribe() method call. Further reading: https://github.com/ReactiveX/RxJava/wiki/Error-Handling | java.lang.IllegalArgumentException: Invalid primitive conversion from long to int
        at com.squareup.receiving.ReceivedResponse$Companion$receiveFromRetrofit$2$2.apply(ReceivedResponse.kt:167)
        at com.squareup.receiving.ReceivedResponse$Companion$receiveFromRetrofit$2$2.apply(ReceivedResponse.kt:105)
        at io.reactivex.internal.operators.single.SingleResumeNext$ResumeMainSingleObserver.onError(SingleResumeNext.java:73)
        at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onError(SingleMap.java:69) 
        at io.reactivex.internal.operators.single.SingleObserveOn$ObserveOnSingleObserver.run(SingleObserveOn.java:79) 
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:209) 
        at android.app.ActivityThread.main(ActivityThread.java:7021) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872) 
     Caused by: java.lang.IllegalArgumentException: Invalid primitive conversion from long to int
        at java.lang.reflect.Field.getInt(Native Method)
        at com.squareup.util.Telephony.<init>(Telephony.java:30)
        at com.squareup.util.Telephony_Factory.get(Telephony_Factory.java:21)
        at com.squareup.util.Telephony_Factory.get(Telephony_Factory.java:8)
        at com.squareup.util.AndroidModule_ProvideNetworkTypeFactory.get(AndroidModule_ProvideNetworkTypeFactory.java:21)
        at com.squareup.util.AndroidModule_ProvideNetworkTypeFactory.get(AndroidModule_ProvideNetworkTypeFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.squareup.server.RegisterHttpInterceptor.intercept(RegisterHttpInterceptor.java:42)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at com.squareup.http.GzipRequestInterceptor.intercept(GzipRequestInterceptor.java:32)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-21 08:49:22.608 10323-10323/com.example.readersdk E/AndroidRuntime:     at com.squareup.server.ProfilingInterceptor.intercept(ProfilingInterceptor.java:24)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at shadow.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at shadow.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at shadow.okhttp3.RealCall.execute(RealCall.java:92)
        at shadow.retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at shadow.retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at shadow.retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:914)
`

**Comment by StephenJosey** [comment]
Hey @anilgorthy thanks for reporting this! We're looking into this and will follow up once we have more information.

**Comment by anilgorthy** [comment]
Any update on this @StephenJosey ? The app crashes on Android Q Beta 2 as well.

**Comment by StephenJosey** [comment]
Hey @anilgorthy, terribly sorry but the delay, but we're still looking into it. With every new Android release, a big concern for us is what's changed from a security point of view; it's not just about getting our code to run. With that said, we are actively working towards making this work and I'll definitely update this thread once I have more information.

**Comment by anilgorthy** [comment]
Great, thank you.

**Comment by ablock** [comment]
We too are seeing this issue on API 29 emulators. Would appreciate an update on resolution. Thanks!

**Comment by anilgorthy** [comment]
So does the

**Comment by davenotdavid** [comment]
@StephenJosey - any updates on this? Can the Reader SDK work on Android Q/10/API 29 and above yet? If so, which Reader SDK version? Because, v1.3.6 throws a security exception as of now.
