### ISSUE TITLE
App crashes on sleep

### ISSUE THREAD

**Issue by krishnakapil** [square/reader-sdk-android-quickstart#14]
When the android device goes to sleep, there is a reader sdk crash.

`Fatal Exception: com.squareup.cardreader.CardReaderAssertException: /project/android/cardreader-native/src/main/jni/cardreader/src/comms/cr_comms_app.c:503. Condition: fail. Message: Message decryption failed with result 14
       at com.squareup.cardreader.lcr.BleBackendNativeJNI.ble_received_data_from_characteristic_data(BleBackendNativeJNI.java)
       at com.squareup.cardreader.lcr.BleBackendNative.ble_received_data_from_characteristic_data(BleBackendNative.java:30)
       at com.squareup.cardreader.lcr.BleBackendNativePassthrough.ble_received_data_from_characteristic_data(BleBackendNativePassthrough.java:32)
       at com.squareup.cardreader.ble.BleBackend.lambda$onDataReceived$1(BleBackend.java:115)
       at com.squareup.cardreader.ble.BleBackend$$Lambda$2.run(Unknown Source:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
       at com.squareup.cardreader.GlobalCardReaderModule$1$1.run(GlobalCardReaderModule.java:76)`

**Comment by StephenJosey** [comment]
Hi @krishnakapil sorry for the delay in response. Since it's been awhile, could you try with the latest Android Reader SDK version (1.3.1) and let me know if you continue to experience the same issue?
