### ISSUE TITLE
Android 10 - BootReceiver RuntimeException

### ISSUE THREAD

**Issue by jonassimonaitis** [square/reader-sdk-android-quickstart#48]
Happy new year! 

We are keep getting randomly an exception from square reader version `readerSdkVersion = "1.5.6"` on **ELO Android 10**

```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.squareup.queue.QueueService$BootReceiver: java.lang.NullPointerException: appContextWrapper must not be null
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3798)
       at android.app.ActivityThread.access$1400(ActivityThread.java:220)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1871)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7397)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by TatsuUkraine** [comment]
Having the same on various devices and various android versions (starting from 9 and up to 13)
